global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-service:8080']
        labels:
          service: 'api-service'
          env: 'local'

  - job_name: 'worker-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker-service:8081']
        labels:
          service: 'worker-service'
          env: 'local'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-collector'
